<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE event [<!ELEMENT zip_code (#PCDATA)><!ELEMENT url_link_display (#PCDATA)><!ELEMENT url (#PCDATA)><!ELEMENT tracks (track+)><!ELEMENT track (#PCDATA)><!ELEMENT title (#PCDATA)><!ELEMENT timeslot (slot_id?, event_id?, title, room, date, start_time, end_date?, end_time, description?, acm_doi?, persons?, tracks?, tags?)><!ELEMENT tags (tag+)><!ELEMENT tag (#PCDATA)><!ELEMENT suffix (#PCDATA)><!ELEMENT subevent_logo_url (#PCDATA)><!ELEMENT subevent_id (#PCDATA)><!ELEMENT subevent (subevent_id?, title, acronym?, subevent_type, description?, room, date, url?, url_link_display?, subevent_logo_url?, acm_doi?, persons?, tracks?, tags?, sponsor?, timeslot*)><!ELEMENT state (#PCDATA)><!ELEMENT start_time (#PCDATA)><!ELEMENT start_date (#PCDATA)><!ELEMENT sponsor (#PCDATA)><!ELEMENT sort_key (#PCDATA)><!ELEMENT slot_id (#PCDATA)><!ELEMENT subevent_type EMPTY><!ATTLIST subevent_type	type (case_study | demonstration | poster | regular | tutorial | workshop) #IMPLIED><!ELEMENT room (#PCDATA)><!ELEMENT role (#PCDATA)><!ELEMENT picture_url (#PCDATA)><!ELEMENT persons (person+)><!ELEMENT person (role, sort_key, first_name, middle_name?, last_name, suffix?, affiliation, acm_profile_id?, email?, bio?, homepage_url?, picture_url?, person_id?)><!ELEMENT middle_name (#PCDATA)><!ELEMENT location (facility_name, facility_map_url?, address, city, state?, country, zip_code?)><!ELEMENT last_name (#PCDATA)><!ELEMENT homepage_url (#PCDATA)><!ELEMENT first_name (#PCDATA)><!ELEMENT facility_name (#PCDATA)><!ELEMENT facility_map_url (#PCDATA)><!ELEMENT event_type EMPTY><!ATTLIST event_type	type (conference|workshop|symposium) #IMPLIED><!ELEMENT event (event_details, subevent*, timeslot*, timezone_id?)><!ELEMENT event_logo_url (#PCDATA)><!ELEMENT event_details (title, acronym, event_type, start_date, end_date, location, description, url?, url_link_display?, event_logo_url?, persons?)><!ELEMENT end_time (#PCDATA)><!ELEMENT end_date (#PCDATA)><!ELEMENT email (#PCDATA)><!ELEMENT description (#PCDATA)><!ELEMENT date (#PCDATA)><!ELEMENT country (#PCDATA)><!ELEMENT city (#PCDATA)><!ELEMENT bio (#PCDATA)><!ELEMENT affiliation (#PCDATA)><!ELEMENT address (#PCDATA)><!ELEMENT acronym (#PCDATA)><!ELEMENT acm_profile_id (#PCDATA)><!ELEMENT acm_doi (#PCDATA)>]>
<event>
  <event_details>
    <title>SPLASH 2021</title>
    <acronym>SPLASH 2021</acronym>
    <event_type type="conference"/>
    <start_date>2021/10/17</start_date>
    <end_date>2021/10/22</end_date>
    <location>
      <facility_name>Swissotel Chicago</facility_name>
      <address>323 East Wacker Drive</address>
      <city>Chicago</city>
      <state>Illinois</state>
      <country>United States</country>
    </location>
    <description>Welcome 
Welcome to SPLASH 2021, the ACM SIGPLAN conference on Systems, Programming, Languages, and Applications: Software for Humanity. SPLASH embraces all aspects of software construction and delivery, to make it the premier conference on the applications of programming languages—at the intersection of programming languages and software engineering. SPLASH takes place Sunday October 17th to Friday 22th. 
SPLASH 2021 registration is now open. Please register using this online registration form. Early registration closes on September 18, 2021. 
SPLASH 2021 will require in-person attendees to be fully vaccinated, as defined by the Center for Disease Control (CDC). According to the CDC, attendees “are considered fully vaccinated (a) 2 weeks after their second dose in a 2-dose series, such as the Pfizer or Moderna vaccines, or (b) 2 weeks after a single-dose vaccine, such as Johnson &amp;amp; Johnson’s Janssen vaccine. If you don’t meet these requirements, regardless of your age, you are NOT fully vaccinated.” SPLASH 2021 will offer virtual attendance options for those individuals who are not fully vaccinated. Vaccination validation will be conducted by a vendor contracted by the ACM to perform this validation for the SPLASH 2021 conference. Masks are required at SPLASH 2021. 
The virtual attendance option is available to unvaccinated attendees.</description>
    <url>https://2021.splashcon.org</url>
    <url_link_display>SPLASH 2021</url_link_display>
    <persons>
      <person>
        <role>Committee Member in Steering Committee, General Chair in Organizing Committee</role>
        <sort_key>1</sort_key>
        <first_name>Hridesh</first_name>
        <last_name>Rajan</last_name>
        <affiliation>Iowa State University</affiliation>
        <bio>Hridesh Rajan is a Professor and Chair of Computer Science at Iowa State University, where he has been since 2005. Professor Rajan earned his MS and Ph.D. from the University of Virginia in 2004 and 2005 respectively. Professor Rajan’s recent research and educational activities are aimed at decreasing the barrier to entry to data-driven sciences to broaden participation. His work on the Boa project is aimed at the invention and refinement of programming languages and cyberinfrastructures that democratize data-driven science &amp;amp; engineering, including software engineering. His work on the Midwest Big Data Summer School is experimenting with broadly accessible data science curricula. Professor Rajan was the founding general chair of the Midwest Big Data Summer School. Professor Rajan’s research interests also include programming language design and implementation, and software engineering. He leads two research projects: Panini, whose goals are to enable modular reasoning about concurrent programs, and Boa that was established in Summer 2012 as an end-to-end infrastructure for analyzing large-scale software repositories and other open data sets. Professor Rajan is the director of the Laboratory for Software Design at Iowa State University, director of graduate admissions and recruitment for the Department of Computer Science. He serves as the department chair of the Department of Computer Science and served as the Professor-In-Charge of the Data Science education programs at Iowa State University from 2017-2019, and chair of the information technology committee for the university from 2015-2019. Professor Rajan served on the steering committee of the Midwest Big Data Hub, a consortium of universities in the Midwest region of the United States focused on promoting data science activities. Professor Rajan is a recipient of the National Science Foundation CAREER award in 2009, LAS Award for Early Achievement in Research in 2010, a Big-12 Fellowship in 2012. He is a 2018-19 Fulbright U.S. Scholar, a AAAS fellow, a distinguished member of the ACM, and a member of IEEE. He is also the inaugural holder of the Kingland Professorship in the Department of Computer Science.</bio>
        <homepage_url>https://hridesh.github.io</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/hrideshrajan/f57a0842-20af-4fd4-b79f-5d673c2c485c/small.jpg</picture_url>
        <person_id>hrideshrajan</person_id>
      </person>
      <person>
        <role>Committee Member in Steering Committee, OOPSLA Review Committee Chair in Organizing Committee</role>
        <sort_key>2</sort_key>
        <first_name>Sophia</first_name>
        <last_name>Drossopoulou</last_name>
        <affiliation>Facebook and Imperial College London</affiliation>
        <bio>I am leading the London Probable team at Facebook, and a Professor of Programming Languages at the Department of Computing, Imperial College, London, UK.</bio>
        <homepage_url>https://wp.doc.ic.ac.uk/sd/</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/sophiadrossopoulou/f9f2890b-55bd-4796-94ab-fe3291277c90/small.jpg</picture_url>
        <person_id>sophiadrossopoulou</person_id>
      </person>
      <person>
        <role>Chair in Steering Committee, SLE General Chair in Organizing Committee</role>
        <sort_key>3</sort_key>
        <first_name>Eelco</first_name>
        <last_name>Visser</last_name>
        <affiliation>Delft University of Technology</affiliation>
        <bio>Eelco Visser is Antoni van Leeuwenhoek Professor of Computer Science and chair of the Programming Languages Group at Delft University of Technology. His current research is on the foundation and implementation of declarative specification of programming languages. He studied at the University of Amsterdam (master 1993; doctorate 1997), and worked at the Oregon Graduate Institute (postdoc 1997-1998), Utrecht University (assistant professor 1998-2006), and TU Delft (associate professor 2006-2013, full professor since 2013). 
His research interests include (domain-specific) programming languages, language engineering, program transformation, and declarative language definition. With his students he has designed and implemented the Spoofax language workbench, as well as several domain-specific languages, including DSLs for syntax definition (SDF3), program transformation (Stratego), static semantics (Statix), software deployment (Nix), and web application development (WebDSL). Applications of WebDSL include the researchr conference hosting site and the WebLab learning management system.</bio>
        <homepage_url>http://eelcovisser.org</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/eelcovisser/3df68e8e-fc37-4ca4-bf4e-132e3d32b392/small.jpg</picture_url>
        <person_id>eelcovisser</person_id>
      </person>
      <person>
        <role>Hybridization Co-Chair in Organizing Committee</role>
        <sort_key>4</sort_key>
        <first_name>Jonathan</first_name>
        <last_name>Aldrich</last_name>
        <affiliation>Carnegie Mellon University</affiliation>
        <bio>Jonathan Aldrich is Associate Professor of Computer Science at Carnegie Mellon University. He is the director of CMU’s Software Engineering Ph.D. program, and teaches courses in programming languages, software engineering, and program analysis for quality and security. In addition, he serves as a consultant on architecture, design, and legal issues in the software industry. Dr. Aldrich joined the CMU faculty after completing a Ph.D. at the University of Washington and a B.S. at Caltech. 
Dr. Aldrich’s research centers on programming languages and type systems that are deeply informed by software engineering considerations. His research contributions include verifying the correct implementation of an architectural design, modular formal reasoning about code, and API protocol specification and verification. For his work on software architecture, Aldrich received a 2006 NSF CAREER award and the 2007 Dahl-Nygaard Junior Prize, given annually for a significant technical contribution to object-oriented programming. He is currently performing research on extensible programming languages, analysis and type systems for security and productivity, and foundations of object-oriented programming.</bio>
        <homepage_url>http://www.cs.cmu.edu/~aldrich/</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/jonathanaldrich/e4add3cf-580c-4d1b-9832-3f7577a14b72/small.jpg</picture_url>
        <person_id>jonathanaldrich</person_id>
      </person>
      <person>
        <role>Hybridization Co-Chair in Organizing Committee</role>
        <sort_key>5</sort_key>
        <first_name>Steve</first_name>
        <last_name>Blackburn</last_name>
        <affiliation>Australian National University</affiliation>
        <bio>My research interests are centered on the challenge of making software run faster and more power-efficiently on modern hardware. My primary interests include: microarchitectural support for managed languages, fast and efficient garbage collection, and the design and implementation of virtual machines. As a backdrop to this I have a longstanding interest in role of sound methodology and infrastructure in successful research innovation.</bio>
        <homepage_url>http://users.cecs.anu.edu.au/~steveb/</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/steveblackburn/1deee732-405d-4403-a974-a418751399c2/small.jpg</picture_url>
        <person_id>steveblackburn</person_id>
      </person>
      <person>
        <role>Hybridization Co-Chair in Organizing Committee</role>
        <sort_key>6</sort_key>
        <first_name>Benjamin</first_name>
        <last_name>Chung</last_name>
        <affiliation>Northeastern University</affiliation>
        <bio>undefined</bio>
        <picture_url>https://2021.splashcon.org/getProfileImage/benjaminchung/30978af0-bcee-4c1e-9dd1-f2588ea14f38/small.jpg</picture_url>
        <person_id>benjaminchung</person_id>
      </person>
      <person>
        <role>Hybridization Co-Chair in Organizing Committee</role>
        <sort_key>7</sort_key>
        <first_name>Youyou</first_name>
        <last_name>Cong</last_name>
        <affiliation>Tokyo Institute of Technology</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://prg.is.titech.ac.jp/people/cong/</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/youyoucong/55f54fd9-cac5-44ae-93c1-921409269efc/small.jpg</picture_url>
        <person_id>youyoucong</person_id>
      </person>
      <person>
        <role>Committee Member in Steering Committee, Hybridization Co-Chair in Organizing Committee</role>
        <sort_key>8</sort_key>
        <first_name>Alex</first_name>
        <last_name>Potanin</last_name>
        <affiliation>Victoria University of Wellington</affiliation>
        <bio>I am an Associate Professor in the School of Engineering and Computer Science at Victoria University of Wellington, New Zealand. 
I am originally from Moscow, Russia with a background in Mathematics. I have completed my PhD in programming languages in 2006 and took up a job as a Lecturer in Software Engineering at Victoria University of Wellington. During my studies, I took short breaks to work as a Visiting Researcher at Purdue University, and Software Engineer at two Wellington start-ups. I spent 2013 on sabbatical at Carnegie Mellon University in Pittsburgh, PA, USA. I spent winter 2019/2020 on sabbatical at Kyoto University in Japan.</bio>
        <homepage_url>http://homepages.ecs.vuw.ac.nz/~alex/</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/alexpotanin/614f887b-90a3-4626-b67d-fa63309b44c8/small.jpg</picture_url>
        <person_id>alexpotanin</person_id>
      </person>
      <person>
        <role>Hybridization Co-Chair in Organizing Committee</role>
        <sort_key>9</sort_key>
        <first_name>Talia</first_name>
        <last_name>Ringer</last_name>
        <affiliation>University of Illinois at Urbana-Champaign</affiliation>
        <bio>I am an incoming assistant professor at University of Illinois at Urbana-Champaign. My main interest is in making program verification using interactive theorem provers more accessible through better proof engineering tools and practices, especially when it comes to maintaining proofs as programs change over time. My vision is a future of verification that is accessible to all programmers, not just to experts. I got my Ph.D. from University of Washington in June 2021, where I was an NSF GRFP fellow and a P.E.O fellow. Prior to graduate school, I earned my bachelor’s in mathematics and computer science from University of Maryland, then worked at Amazon as a software engineer for three years. I am the founder and chair of the SIGPLAN-M mentoring program, and a contributor to the Coq interactive theorem prover. 
Oh, and I am currently looking for students! Please apply!</bio>
        <homepage_url>https://dependenttyp.es</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/taliaringer/1a95a492-cf5a-4225-8efb-ac834a36fa16/small.jpg</picture_url>
        <person_id>taliaringer</person_id>
      </person>
      <person>
        <role>Onward! Essays Chair in Organizing Committee</role>
        <sort_key>10</sort_key>
        <first_name>Elisa</first_name>
        <last_name>Baniassad</last_name>
        <affiliation>University of British Columbia</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.cs.ubc.ca/~ebani</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/elisabaniassad/ebb453ca-88ce-4678-823e-82b113c14751/small.jpg</picture_url>
        <person_id>elisabaniassad</person_id>
      </person>
      <person>
        <role>Committee Member in Steering Committee, Onward! Papers Chair in Organizing Committee</role>
        <sort_key>11</sort_key>
        <first_name>Wolfgang</first_name>
        <last_name>De Meuter</last_name>
        <affiliation>Vrije Universiteit Brussel</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://soft.vub.ac.be/soft/users/wdmeuter</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/wolfgangdemeuter/cb721b79-a1aa-4583-8ba0-b1a96f896900/small.jpg</picture_url>
        <person_id>wolfgangdemeuter</person_id>
      </person>
      <person>
        <role>DLS Chair in Organizing Committee</role>
        <sort_key>12</sort_key>
        <first_name>Arjun</first_name>
        <last_name>Guha</last_name>
        <affiliation>Northeastern University</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://khoury.northeastern.edu/~arjunguha</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/arjunguha/284e0782-ec24-4ad9-b6a4-b6a1d0e2fe9a/small.jpg</picture_url>
        <person_id>arjunguha</person_id>
      </person>
      <person>
        <role>SPLASH-E Co-Chair in Organizing Committee</role>
        <sort_key>13</sort_key>
        <first_name>Charlie</first_name>
        <last_name>Curtsinger</last_name>
        <affiliation>Grinnell College</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://ccurtsinger.net</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/charliecurtsinger/e779a4c9-ade3-4073-b660-866046d6c953/small.jpg</picture_url>
        <person_id>charliecurtsinger</person_id>
      </person>
      <person>
        <role>SPLASH-E Co-Chair in Organizing Committee</role>
        <sort_key>14</sort_key>
        <first_name>Tien N.</first_name>
        <last_name>Nguyen</last_name>
        <affiliation>University of Texas at Dallas</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.utdallas.edu/~tien.n.nguyen/</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/tiennguyen/10e4533a-6059-499a-aa1c-a76131caeae5/small.jpg</picture_url>
        <person_id>tiennguyen</person_id>
      </person>
      <person>
        <role>Doctoral Symposium Chair in Organizing Committee</role>
        <sort_key>15</sort_key>
        <first_name>Robert</first_name>
        <last_name>Dyer</last_name>
        <affiliation>University of Nebraska-Lincoln</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://go.unl.edu/rdyer</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/robertdyer/774d6fd8-9a08-4c37-9113-f0bc0c5fb833/small.jpg</picture_url>
        <person_id>robertdyer</person_id>
      </person>
      <person>
        <role>Committee Member in Steering Committee, Rebase Chair in Organizing Committee</role>
        <sort_key>16</sort_key>
        <first_name>Jan</first_name>
        <last_name>Vitek</last_name>
        <affiliation>Northeastern University / Czech Technical University</affiliation>
        <bio>Jan Vitek is a Professor of Computer Science at Northeastern University. Dr. Vitek was born in Czechoslovakia and educated in Switzerland. Over the years, he worked on topics related to programming languages, their design, use, and implementation. With Noble and Potter, he proposed the notion of flexible alias control which became know as Ownership Types. He led the Ovm project which produced the first real-time Java virtual machine to be flight tested on a ScanEagle drone (he claims no one was harmed). Outcomes of this project include the Schism real-time garbage collector and the FijiVM – a production VM for embedded systems. More recently, he worked on dynamic languages, trying to make sense of JavaScript and to design a new language called, Thorn. Nowadays, he spends his time with statisticians and data scientists. Jan believes that his 2012 election as Chair of SIGPLAN was an accident; since has been busy trying to rock the boat to ensure this does not happen again. In his spare time, Jan enjoys organizing conferences and sitting on PCs (over 25 in the last decade). He founded the MOS (mobile objects), IWACO (alias control), STOP (gradual typing), and TRANSACT (transactional memory) workshop series. He was the first program chair of VEE and chaired ESOP, ECOOP, Coordination and TOOLS. He was the general chair of PLDI (in Beijing!), ISMM and LCTES. He may still be sitting on the steering committees of ECOOP, JTRES, ICFP, OOPLSA, POPL, PLDI, LCTES, ESOP.</bio>
        <homepage_url>http://janvitek.org</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/janvitek/213b9734-8942-47ea-933d-6ffad4bb1ee6/small.jpg</picture_url>
        <person_id>janvitek</person_id>
      </person>
      <person>
        <role>Workshops Co-Chair in Organizing Committee</role>
        <sort_key>17</sort_key>
        <first_name>Mehdi</first_name>
        <last_name>Bagherzadeh</last_name>
        <affiliation>Oakland University</affiliation>
        <bio>Assistant Professor, Department of Computer Science and Engineering</bio>
        <homepage_url>https://mbagherz.bitbucket.io/</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/mehdibagherzadeh/95dc6f53-51a0-4bf1-b822-7bbe8c4d223a/small.jpg</picture_url>
        <person_id>mehdibagherzadeh</person_id>
      </person>
      <person>
        <role>Workshops Co-Chair in Organizing Committee</role>
        <sort_key>18</sort_key>
        <first_name>Raffi</first_name>
        <last_name>Khatchadourian</last_name>
        <affiliation>CUNY Hunter College</affiliation>
        <bio>I am an Assistant Professor in the Department of Computer Science at Hunter College and the Graduate Center of the City University of New York (CUNY). My research is centered on techniques for automated software evolution, particularly those related to automated refactoring and source code recommendation systems. My goal is to ease the burden associated with correctly and efficiently evolving large and complex software by providing automated tools that can be easily used by developers. I am also interested in the automated analysis of Object-Oriented programs. 
I received my MS and Ph.D. degrees in Computer Science from Ohio State University and my BS degree in Computer Science from Monmouth University in New Jersey. Prior to joining CUNY, I was a Software Engineer at Apple, Inc. in Cupertino, California, where I worked on Digital Rights Management (DRM) for iTunes, iBooks, and the App Store. I also developed distributed software that tested various features of iPhones, iPads, and iPods. You may also find more information about me by visiting my CUNY Academic Commons profile, my vita, GitHub, and my blog (you can subscribe for updates here).</bio>
        <homepage_url>http://cs.hunter.cuny.edu/~Raffi.Khatchadourian99</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/raffikhatchadourian/5c884f46-e4aa-4dc5-b581-2e37f77d320a/small.jpg</picture_url>
        <person_id>raffikhatchadourian</person_id>
      </person>
      <person>
        <role>Student Research Competition Co-Chair in Organizing Committee</role>
        <sort_key>19</sort_key>
        <first_name>Julia</first_name>
        <last_name>Rubin</last_name>
        <affiliation>University of British Columbia</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.ece.ubc.ca/~mjulia/</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/juliarubin/5846079d-0c90-4d9a-8f16-eef07002e37d/small.jpg</picture_url>
        <person_id>juliarubin</person_id>
      </person>
      <person>
        <role>Student Research Competition Co-Chair in Organizing Committee</role>
        <sort_key>20</sort_key>
        <first_name>Caterina</first_name>
        <last_name>Urban</last_name>
        <affiliation>INRIA &amp; École Normale Supérieure | Université PSL</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://caterinaurban.github.io</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/caterinaurban1/a945f9bd-bc13-4fe2-945a-59528d7d7e2a/small.jpg</picture_url>
        <person_id>caterinaurban1</person_id>
      </person>
      <person>
        <role>Publicity Chair in Organizing Committee</role>
        <sort_key>21</sort_key>
        <first_name>Juan</first_name>
        <last_name>Fumero</last_name>
        <affiliation>University of Manchester, UK</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://jjfumero.github.io</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/juanfumero/e76896d1-7e40-4e77-859f-dc51392013a2/small.jpg</picture_url>
        <person_id>juanfumero</person_id>
      </person>
      <person>
        <role>Web Chair in Organizing Committee</role>
        <sort_key>22</sort_key>
        <first_name>Rangeet</first_name>
        <last_name>Pan</last_name>
        <affiliation>Iowa State University, USA</affiliation>
        <bio>Rangeet Pan is a Ph.D. candidate at Iowa State University. His research interests include program analysis, machine learning, and software engineering. He has published works at ESEC/FSE and ICSE.</bio>
        <homepage_url>https://rangeetpan.github.io/</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/rangeetpan/3f0551cd-7e73-4053-bb36-66f8d05daae5/small.jpg</picture_url>
        <person_id>rangeetpan</person_id>
      </person>
      <person>
        <role>Student Volunteer Co-Chair in Organizing Committee</role>
        <sort_key>23</sort_key>
        <first_name>Breno</first_name>
        <last_name>Dantas Cruz</last_name>
        <affiliation>Virginia Tech</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://people.cs.vt.edu/~bdantasc/</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/brenodantascruz/7407f1b4-cf3d-4a2e-8c5e-3a49f0405e8f/small.jpg</picture_url>
        <person_id>brenodantascruz</person_id>
      </person>
      <person>
        <role>Student Volunteer Co-Chair in Organizing Committee</role>
        <sort_key>24</sort_key>
        <first_name>Samantha Syeda</first_name>
        <last_name>Khairunnesa</last_name>
        <affiliation>Florida Gulf Coast University</affiliation>
        <bio>Samantha Syeda Khairunnesa, Ph.D., is the Assistant Professor in the Department of Software Engineering at Florida Gulf Coast University, where she has been since August 2021. She earned her Ph.D. in Computer Science from Iowa State University in August 2021. She specializes in software engineering, programming languages, and machine learning.</bio>
        <homepage_url>https://www.linkedin.com/in/samantha-syeda/</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/samanthasyedakhairunnesa/23aa8334-ebf0-4967-b8ab-6d4cbf1509c5/small.jpg</picture_url>
        <person_id>samanthasyedakhairunnesa</person_id>
      </person>
      <person>
        <role>Sponsorship Co-Chair in Organizing Committee</role>
        <sort_key>25</sort_key>
        <first_name>Ganesha</first_name>
        <last_name>Upadhyaya</last_name>
        <affiliation>Harmony.one</affiliation>
        <bio>I am currently a Research Engineer at Harmony.one, Mountain View, CA. I work on blockchain network, protocol, and smart contract verification. Previously, I was a Senior Staff Researcher at Futurewei Technologies (Huawei R&amp;amp;D), Champaign, IL, where I worked on researching and developing compiler, runtime, and frameworks for Huawei’s mobile, cloud, and IoT solutions. In addition, impactful software engineering research has always been my passion.</bio>
        <homepage_url>http://web.cs.iastate.edu/~ganeshau/</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/ganeshaupadhyaya/e4cda76a-77e7-4064-a67e-a85da0616702/small.jpg</picture_url>
        <person_id>ganeshaupadhyaya</person_id>
      </person>
      <person>
        <role>Poster Co-Chair in Organizing Committee</role>
        <sort_key>26</sort_key>
        <first_name>Christos</first_name>
        <last_name>Dimoulas</last_name>
        <affiliation>PLT @ Northwestern University</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://users.eecs.northwestern.edu/~chrdimo/</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/christosdimoulas1/b0a0a408-c992-49cf-99f4-39e30fe9ce1d/small.jpg</picture_url>
        <person_id>christosdimoulas1</person_id>
      </person>
      <person>
        <role>Poster Co-Chair in Organizing Committee</role>
        <sort_key>27</sort_key>
        <first_name>Murali</first_name>
        <last_name>Krishna Ramanathan</last_name>
        <affiliation>Uber Technologies Inc.</affiliation>
        <bio>Murali Krishna Ramanathan is a Staff Software Engineer at Uber Technologies Inc. Previously, he was affiliated with IISc, Bangalore and Coverity Inc. He has designed and implemented several novel program analysis tools for detecting software bugs. He received his PhD in Computer Science from Purdue University.</bio>
        <homepage_url>https://sites.google.com/view/mkramanathan/</homepage_url>
        <picture_url>https://2021.splashcon.org/getProfileImage/muralikrishnaramanathan/52304999-046a-4d35-a2ed-9eb9ca2db709/small.jpg</picture_url>
        <person_id>muralikrishnaramanathan</person_id>
      </person>